package com.rentit.demo.controller;

import com.rentit.demo.model.Renter;
import com.rentit.demo.repository.RenterRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.text.MessageFormat;
import java.util.Optional;

@RestController
@CrossOrigin(origins = "https://safe-sierra-04090.herokuapp.com/")
@RequestMapping(path = "/api/v1")
public class RenterController {

    @Autowired// This means to get the bean called renterRepository which is auto-generated by Spring
    private RenterRepository repository;

    @GetMapping(path = "/renters")
    public @ResponseBody Iterable<Renter> getAllRenters() {
        return repository.findAll(); // This returns a JSON or XML with the renters
    }

    @GetMapping(path = "/renters/{id}")
    public Optional<Renter> getRenter(@PathVariable("id") Integer id) {
        return repository.findById(id);
    }

    @PostMapping(path = "/renters")
    public Renter createRenter(@RequestBody Renter renter) {
        return repository.save(renter);
    }

    @PutMapping(path = "/renters")
    public Renter updateRenter(@RequestBody Renter renter) {
        return repository.save(renter);
    }

    @DeleteMapping(path = "/renters/{id}")
    @ResponseBody
    public String deleteRenter(@PathVariable("id") Integer id) throws Exception {
        repository.deleteById(id);
        return MessageFormat.format("Renter with ID {0} has been deleted.", id);
    }
}
